CANopen2CalibratorGUIAdapter/Controllers/LssController.cs
using System.Linq;
using CANopen2CalibratorGUIAdapter.CANOpenClient;
using CANopen2CalibratorGUIAdapter.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CANopen2CalibratorGUIAdapter.Controllers
{
    public class LssController : Controller
    {
        #region Fields

        private readonly ILogger<LssController> _logger;
        private readonly IBackendClient Backend;

        #endregion Fields

        #region Constructors

        public LssController(IBackendClient backend, ILogger<LssController> logger)
        {
            Backend = backend;
            _logger = logger;
        }

        #endregion Constructors

        #region Methods

        [HttpGet]
        public IActionResult Index()
        {
            return base.View(new LssModel
            {
                Connected = Backend.Connected,
                SpeedSetupSupported = Backend.SpeedSetupSupported,
                CurrentSpeedGrade = Backend.SpeedID,

                CurrentNetworkConfig = GetNetworkConfigString()
            });
        }

        [HttpGet]
        public IActionResult NetworkConfig() => Content(GetNetworkConfigString());

        private string GetNetworkConfigString() => string.Join("\n",
                    Backend.Devices.GetAliveDeviceList().Select(x => $"{x.LSSId.ToShortString()}={x.NodeID}"));

        #endregion Methods
    }
}

CANopen2CalibratorGUIAdapter/Controllers/OverviewController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using CANopen2CalibratorGUIAdapter.CANOpenClient;
using CANopen2CalibratorGUIAdapter.Models;
using CANopen2CalibratorGUIAdapter.Models.DeviceCardModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CANopen2CalibratorGUIAdapter.Controllers
{
    public class OverviewController : Controller
    {
        private readonly ILogger<OverviewController> _logger;
        private readonly IBackendClient Backend;

        public OverviewController(IBackendClient backend, ILogger<OverviewController> logger)
        {
            Backend = backend;
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(new OverwiewModel
            {
                Connected = Backend.Connected,
            });
        }

        public IActionResult NodeCard(int id)
        {
            var Node = Backend.Devices[(byte)id];

            return Node != null ? ViewComponent("DeviceListItem", new DeviceListItem
            {
                NodeID = Node.NodeID,
                LSSId = Node.LSSId,
                NMTState = Node.State,

                BootloaderController = Node.BootloaderController,

                DeviceKnown = Node.IsKnownDevice,
                VendorString = Node.GetVendorString(),
                ProductString = Node.GetProductString(),
                TimeFromLastHeartbeat = DateTime.Now - Node.LastHBTimestamp,
                EdsInfo = Node.Eds
            }) : null;
        }

        [HttpGet]
        public IActionResult Cards() => ViewComponent("DeviceList");

        [HttpGet]
        public async Task<IActionResult> GetTPDOMapping(int id)
        {
            var TPDO = Backend.Devices[(byte)id]?.TPDO;
            if (TPDO == null)
            {
                return Json(new { records = new object[0], total = 0 });
            }
            var config = await TPDO.TPDOConfig();
            var table = (from slot in config
                         where !slot.invalid
                         from index in slot.Mapping
                         select new TPDOItem
                         {
                             Index = $"{index.Index:X}sub{index.Subindex}",
                             Name = index.parameter_name,
                             Value = "N/A",
                             Timestamp = null
                         }).ToArray();

            return Json(new { records = table, total = table.Count() });
        }
    }
}

CANopen2CalibratorGUIAdapter/Controllers/SYNCController.cs
using System.Threading.Tasks;
using CANopen2CalibratorGUIAdapter.CANOpenClient;
using CANopen2CalibratorGUIAdapter.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CANopen2CalibratorGUIAdapter.Controllers
{
    public class SYNCController : Controller
    {
        private readonly IBackendClient Backend;
        public ILogger<SYNCController> _logger;

        public SYNCController(IBackendClient backend, ILogger<SYNCController> logger)
        {
            Backend = backend;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            if (!Backend.Connected)
            {
                return View(null);
            }

            var config = await Backend.GetSyncConfig();
            if (config.Failure)
            {
                _logger.LogError($"Failed to get SYNC config: {config.Error}");
                return View("Error", config.Error);
            }
            else
            {
                _logger.LogInformation($"Current SYNC config: {config.Value}");
                return View(config.Value);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Configure(SYNCConfig config)
        {
            _logger.LogWarning($"Updating SYNC config: {config}...");
            var res = await Backend.SetSyncConfig(config);
            if (res.Failure)
            {
                _logger.LogError($"Failed: {res.Error}");
            }
            return RedirectToAction("Index");
        }
    }
}

CANopen2CalibratorGUIAdapter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CANopen2CalibratorGUIAdapter</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" asp-append-version="true" />
    @RenderSection("styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/CANopen.png" height="40" width="120" style="margin-top:0px;">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" id="nav-bar-connection">
                            <a class="nav-link" asp-area="" asp-controller="Connection" asp-action="Index">Подключение</a>
                        </li>
                        <li class="nav-item" id="nav-bar-overview">
                            <a class="nav-link" asp-area="" asp-controller="Overview" asp-action="Index">Обзор</a>
                        </li>
                        <li class="nav-item" id="nav-bar-lss">
                            <a class="nav-link" asp-area="" asp-controller="Lss" asp-action="Index">LSS</a>
                        </li>
                        <li class="nav-item" id="nav-bar-sync">
                            <a class="nav-link" asp-area="" asp-controller="SYNC" asp-action="Index">SYNC</a>
                        </li>
                        <li class="nav-item" id="nav-bar-emergency">
                            <a class="nav-link" asp-area="" asp-controller="Emergency" asp-action="Index">Emergency</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/lib/font-awesome/js/all.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-noty/packaged/jquery.noty.packaged.min.js" asp-append-version="true"></script>
    <script src="~/ts-js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>